import React, { useEffect } from 'react';
import '../App.css'
import Navbar from './PrivacyNavbar';

export default function Terms() {
    function totop() {
        window.scrollTo(0, 0)

    }
    useEffect(() => {
        totop()

        return () => {
        };
    }, []);

    return (
        <>
            <div className="privacy">
                <div className="header4">
                    <Navbar />
                    <div id="privacy" className="container col-xxl-10 px-4 py-5">
                        <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
                            <div className="col-lg-12">
                                <center><h1 className="bs-text-size fw-bold lh-1 mb-3 text-white"> <i>TERMS & CONDITIONS</i></h1></center>
                                <p className="lead text-white">
                                    This website is owned and operated by Kinsmen Capital Pty Ltd (ACN 653 514 231), which is the owner of the Women of Africa NFT concept, design and all associated intellectual property (“IP”) including the domain name womenofafrica.io. Throughout the site and these Terms & Conditions, the term "we", "us", “our”, “Company", “WoA”, “womenofafrica.io”, “KC” as the context may require, refer to Kinsmen Capital Pty Ltd. By visiting our site and/or purchasing something from us, you engage in our service (“Service”) and agree to be bound by the following terms and conditions (“Terms”).
                                </p>
                                <p className="lead text-white">
                                    We reserve the right to update, change or replace any part of these Terms of services without prior written notice at any time, and it is your responsibility to periodically review these Terms to stay informed of updates. Any changes to the Terms will be in effect as of the last updated referenced on the site and at the top of these Terms.
                                </p>
                                <p className="lead text-white">
                                    Your continued use of this site after the last updated date will constitute your acceptance of agreement.
                                </p>
                                <p className="lead text-white">
                                    By visiting the website of our products merchants, in particular <a href='https://opensea.io/'>www.opensea.io</a> or <a href='https://clubvirtual.io/'>clubvirtual.io</a> as the case may be, you also engage and agree to be bound by their terms and conditions.
                                </p>
                                <p className="lead text-white">
                                    This website is for informational purposes and serves as a binding contract for purchasers of WoA NFTs.
                                </p>
                                <p className="lead text-white">
                                    WoA NFTs is a generative collection of digital artwork (NFTs) housed and run on the Ethereum Network. Users and collector of these NFTs are solely responsible for the safety and the management of their own private assets, which include but are not limited to Ethereum wallets, validating all transactions and contracts generated by this website prior to and after purchases.
                                </p>
                                <p className="lead text-white">
                                    Users certify through purchase that they understand that, as the WoA smart contract runs on the Ethereum network and is bound by their system and terms, there is no ability to undo, reverse, or restore any transactions.
                                </p>
                                <p className="lead text-white">
                                    Any connected services included this website are provided “as is” and “as available” without any warranty of any kind. Use of this website constitutes your agreement that you are accepting sole responsibility for any and all transactions involving WoA digital collectibles.
                                </p>
                                <p className="lead text-white">
                                    By agreeing to these Terms, you represent that you are at least the age of majority in your state or province of residence.
                                </p>
                                <p className="lead text-white">
                                    You may not use our products and/or services for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).
                                </p>

                                <p className="lead text-white bs-text-bold">
                                    <b className='bold'> OWNERSHIP, USAGE & IP</b>
                                </p>
                                <p className="lead text-white">When you purchase your WoA NFT, you own the NFT. The ownership is transferred to you on the Ethereum blockchain for that individual piece of art, combination of traits and number. Ownership of the NFT is ruled by the smart contract and the Ethereum Network terms. We have no ability to alter, freeze, seize or modify the ownership of any WoA NFT.</p>
                                <p className="lead text-white">All buyers acknowledge and agree that, following the purchase of any WoA NFT on the website, they do not have any legal ownership right, or title to any copyrights, trademarks or other intellectual property rights to the underlying artwork of the WoA NFT. All copyrights and intellectual property rights in the underlying artwork shall remain vested in KC, including but not limited to the right to reproduce, to prepare derivative works, to display, to perform and to distribute the artworks.</p>
                                <p className="lead text-white">Following the purchase of a WoA NFT on the website, the buyer may display or perform the WoA NFT publicly or privately for the purposes of promoting, sharing, discussing or commenting on the buyer’s purchase, ownership or interest in the WoA NFT.</p>
                                <p className="lead text-white">The buyer of the WoA NFT may display or perform the NFT on:</p>
                                <p className="lead text-white">
                                    <ul>
                                        <li>third party platforms in association with an offer to sell or trade the NFT; and</li>
                                        <li>within decentralised virtual environments (including other NFT marketplaces, virtual or physical galleries and virtual or physical museums).</li>
                                    </ul>
                                </p>
                                <p className="lead text-white">The buyer acknowledges and agrees that it may not, nor permit any third party, without the prior written consent of KC:</p>
                                <p className="lead text-white">
                                    <ul>
                                        <li>make “commercial use” of any underlying artwork to the NFT including by selling copies of, access to the artwork or otherwise commercially exploiting the artwork;</li>
                                        <li>modify or distort the artwork in a way which would be prejudicial to KC interests;</li>
                                        <li>use the artwork to advertise, market or sell any third-party product or service;</li>
                                        <li>use the artwork in connection with any form of media that depicts hatred, intolerance, violence, cruelty or anything else that may be considered hate speech;</li>
                                        <li>sell, distribute for commercial gain, or otherwise commercialise merchandise that includes the artwork;</li>
                                        <li>attempt to trademark, copyright or otherwise acquire additional intellectual property rights in or to the artwork;</li>
                                        <li>attempt to mint an NFT representing the same artwork; and </li>
                                        <li>falsify, misrepresent, or conceal the ownership of the artwork or the NFT.</li>
                                    </ul>
                                </p>
                                <p className="lead text-white bs-text-bold">
                                    <b className='bold'>FEEDBACK</b>
                                </p>
                                <p className="lead text-white">
                                    You can submit comments, bug reports, ideas about the site or the project. By submitting any feedback, you agree that we are free to use same in any way we choose without additional compensation to you and you hereby grant us a perpetual, irrevocable, nonexclusive worldwide licence to incorporate and use the feedback for any purpose.
                                </p>
                                <div className="d-grid gap-2 d-md-flex justify-content-md-start">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </>
    )
}
